[package]
name = "fs-tracers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.6"
futures = "0.3"
libc = "0.2.166"
nix = { features = ["event", "fanotify", "fs"], git = "https://github.com/carlvoller/nix", branch = "handle_fix" }
thiserror = "1.0.64"
tokio = { version = "1.41.1", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
tokio-util = "0.7.13"

