[package]
name = "fs-tracers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.6"
bitflags = "2.6.0"
futures = "0.3"
libc = "0.2.166"
nix = { version = "0.29.0", features = ["fanotify", "fs"] }
thiserror = "1.0.64"
tokio = { version = "1.41.1", features = ["macros", "net", "rt", "sync"] }
